### ISSUE TITLE
Support SP110E

### ISSUE THREAD

**Issue by ilker-aktuna** [monty68/uniled#4]
SP110E is very similar to SP107E
It just lacks the audio feature.
Is it possible to add it ?
Currently component detects and adds a light but can not start it.

**Comment by monty68** [comment]
I have an SP110E device but have not had time yet to investigate it and its protocol.

**Comment by ilker-aktuna** [comment]
can I help in development of this ?
I have a bluetooth sniffer. If I find the advertisement packet  and the commands sent to the device from the app, can we integrate this easily ?

**Comment by BlockArchitech** [comment]
You could give it a shot, I don't see why not (That is the beauty of open source after all). I'm sure that packets being sent are exactly the same though. Could you try turning it on in the app, then trying to change the color in HA?

**Comment by ilker-aktuna** [comment]
different brightness settings:
middle:
8cf38b2a
brighter:
b290562a

different speed settings:
min:
002ec903
max:
ff98ee03
mid:
82364a03

**Comment by monty68** [comment]
I have all the protocol details captured, just don't have time at the moment as dealing with family
issues, but imagine something in the next week or so

**Comment by monty68** [comment]
v0.2.0 Beta should now support SP110E devices, please download, install and test.

**Comment by ilker-aktuna** [comment]
oh. that was fast. I'll try in a few hours.

**Comment by ilker-aktuna** [comment]
btw, I have a question not related to this subject but I don't want to add another "open issue" which is unnecessary. I could not find another way to contact you. so, I'll ask here. (I'm really sorry)
is it possible to control 2 or more of these devices' effect effect speed on a single slider ?
I combined them under a light group and I am able to control their brightness using an entity card for that group.
But that does not let me control effect speed.
any ideas ?

**Comment by monty68** [comment]
> btw, I have a question not related to this subject but I don't want to add another "open issue" which is unnecessary. I could not find another way to contact you. so, I'll ask here. (I'm really sorry) is it possible to control 2 or more of these devices' effect effect speed on a single slider ? I combined them under a light group and I am able to control their brightness using an entity card for that group. But that does not let me control effect speed. any ideas ?

You can use a service call to UniLED triggered by a helper input_number to set the speed of two light entities.

`
# Example configuration.yaml entry using 'input_number' in an action in an automation to set the effect speed for two UniLED lights
input_number:
  master_speed:
    name: Speed
    initial: 125
    min: 1
    max: 255
    step: 1
automation:
  - alias: "Master Effect Speed - Custom"
    trigger:
      platform: state
      entity_id: input_number.master_speed
    action:
      - service: uniled.set_state
        target:
          entity_id: light.sp110e_light1
        data:
          effect_speed: "{{ states('input_number.master_speed') | int }}"
      - service: uniled.set_state
        target:
          entity_id: light.sp110e_light2
        data:
          effect_speed: "{{ states('input_number.master_speed') | int }}"
`

**Comment by monty68** [comment]
> I could not find another way to contact you. 

[https://community.home-assistant.io/t/custom-component-uniled-support-for-ble-pixel-controllers-sp107e-sp110e-sp601e-sp611e-sp6117e/490399](UniLED Post)

**Comment by ilker-aktuna** [comment]
> v0.2.1 Beta should now support SP110E devices, please download, install and test.

I just tested this. Works fine. 
And I grouped them all. On/off , brightness commands work well together on sp107e and sp110e

Just the effects are different. So for example, on sp107e , "Pattern FX 42" is similar to "Pattern 71" on sp110e.
If there was a way to match similar effects together, it would be awesome.

**Comment by ilker-aktuna** [comment]
> > btw, I have a question not related to this subject but I don't want to add another "open issue" which is unnecessary. I could not find another way to contact you. so, I'll ask here. (I'm really sorry) is it possible to control 2 or more of these devices' effect effect speed on a single slider ? I combined them under a light group and I am able to control their brightness using an entity card for that group. But that does not let me control effect speed. any ideas ?
> 
> You can use a service call to UniLED triggered by a helper input_number to set the speed of two light entities.
> 
> ```yaml
> # Example configuration.yaml entry using a helper 'input_number' entity in 
> # an automation to set the effect speed for two UniLED lights
> 
> input_number:
>   master_speed:
>     name: Master Speed
>     initial: 125
>     min: 1
>     max: 255
>     step: 1
> automation:
>   - alias: "Master Effect Speed - Custom"
>     trigger:
>       platform: state
>       entity_id: input_number.master_speed
>     action:
>       - service: uniled.set_state
>         target:
>           entity_id: light.sp110e_light1
>         data:
>           effect_speed: "{{ states('input_number.master_speed') | int }}"
>       - service: uniled.set_state
>         target:
>           entity_id: light.sp110e_light2
>         data:
>           effect_speed: "{{ states('input_number.master_speed') | int }}"
> ```

I just tried this now. But setting master speed does not change the effect speed for listed lights.

Should I use:

```
 - service: uniled.set_state
        target:
          entity_id: light.sp107e_int
        data:
          effect_speed: "{{ states('input_number.master_speed') | int }}"
```

OR
```

      - service: uniled.set_state
        target:
          entity_id: number.sp110e_effect_speed
        data:
          effect_speed: "{{ states('input_number.master_speed') | int }}"


```

**Comment by monty68** [comment]
The service calls only work against the light entity so the first one.

Check your configuration.yaml, if this is importing automations from a separate file, e.g. a line with 

```yaml automation: !include automations.yaml```

If this is the case you will have to move the automation code into the automations.yaml file.

**Comment by monty68** [comment]
> yes, you are correct.
> the automations.yaml has only [] in it.
> How should I put the code in that file ?
> 

[https://www.home-assistant.io/docs/automation/yaml/](url)

**Comment by monty68** [comment]
> > v0.2.1 Beta should now support SP110E devices, please download, install and test.
> 
> I just tested this. Works fine. 
> And I grouped them all. On/off , brightness commands work well together on sp107e and sp110e
> 
> Just the effects are different. So for example, on sp107e , "Pattern FX 42" is similar to "Pattern 71" on sp110e.
> If there was a way to match similar effects together, it would be awesome.
> 
> 

This is beyond the scope of this integration, suggest you look at setting up scene's

**Comment by ilker-aktuna** [comment]
ok. I got the correct yaml for the automation now.

```
- id: '1670866628751'
  alias: Strips Speed
  description: strips speed
  trigger:
  - platform: state
    entity_id:
    - input_number.master_speed
  condition: []
  action:
  - service: uniled.set_state
    data:
      effect_speed: "{{ states('input_number.master_speed') | int }}"
    target:
      entity_id: light.sp110e_light
  - service: uniled.set_state
    data:
      effect_speed: "{{ states('input_number.master_speed') | int * 186 / 255 }}"
    target:
      entity_id: light.sp107e_ext_light
  - service: uniled.set_state
    data:
      effect_speed: "{{ states('input_number.master_speed') | int * 186 / 255 }}"
    target:
      entity_id: light.sp107e_int_light
  mode: parallel

```

this works just fine.
But there is no "effect mode" entity available for sp110e
If I group them, and change the group's effect mode (pattern) it changes the sp110e effect pattern, but there is no direct effect mode setting for sp110e
